export interface UserTraveler {
  _id?: string; // Optional, as it might be generated by MongoDB
  email: string;
  password: string; // Always hashed
  firstName?: string; 
  lastName?: string; 
  phoneNumber?: string;
  birthDate?: Date; 
  lastSignin?: Date;
  lastSigninIp?: string;
  failedSignins?: number;
  createdAt?: Date;
  updatedAt?: Date;
}
