name: Deploy to Cloud Run
on:
  push:
    branches:
      - main
      - uat
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: actota-frontend
  REGION: us-central1
  # Define these here for clarity, they will be accessed correctly in the job steps
  NODE_ENV: ${{vars.NODE_ENV}}
  NEXT_PUBLIC_API_URL: ${{vars.NEXT_PUBLIC_API_URL}}
  NEXT_TELEMETRY_DISABLED: 1
  NEXTAUTH_URL: ${{vars.NEXTAUTH_URL}}
  NEXT_PUBLIC_GOOGLE_MAPS_KEY: ${{secrets.NEXT_PUBLIC_GOOGLE_MAPS_KEY}}
  NEXT_PUBLIC_AUTH_SECRET: ${{secrets.NEXT_PUBLIC_AUTH_SECRET}}
jobs:
  deploy-uat:
    if: github.ref == 'refs/heads/uat'
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      # Build the Docker image, passing build arguments with proper GitHub expression syntax
      - name: Build
        run: |
          docker build \
            --build-arg NODE_ENV="${{ env.NODE_ENV }}" \
            --build-arg NEXT_PUBLIC_API_URL="${{ env.NEXT_PUBLIC_API_URL }}" \
            --build-arg NEXTAUTH_URL="${{ env.NEXTAUTH_URL }}" \
            --build-arg NEXT_PUBLIC_GOOGLE_MAPS_KEY="${{ env.NEXT_PUBLIC_GOOGLE_MAPS_KEY }}" \
            --build-arg NEXT_PUBLIC_AUTH_SECRET="${{ env.NEXT_PUBLIC_AUTH_SECRET }}" \
            -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA .
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet
      - name: Push
        run: docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA
      - name: Deploy
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated # Adjust
  deploy-prod:
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      environment: production
      steps:
        - uses: actions/checkout@v3
        - id: 'auth'
          uses: 'google-github-actions/auth@v1'
          with:
            credentials_json: '${{ secrets.GCP_SA_KEY }}'
        - name: Build
          run: |
            docker build \
              --build-arg NODE_ENV="${{ env.NODE_ENV }}" \
              --build-arg NEXT_PUBLIC_API_URL="${{ env.NEXT_PUBLIC_API_URL }}" \
              --build-arg NEXTAUTH_URL="${{ env.NEXTAUTH_URL }}" \
              --build-arg NEXT_PUBLIC_GOOGLE_MAPS_KEY="${{ env.NEXT_PUBLIC_GOOGLE_MAPS_KEY }}" \
              --build-arg NEXT_PUBLIC_AUTH_SECRET="${{ env.NEXT_PUBLIC_AUTH_SECRET }}" \
              -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA .
        - name: Configure Docker
          run: gcloud auth configure-docker --quiet
        - name: Push
          run: docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA
        - name: Deploy
          run: |
            gcloud run deploy ${{ env.SERVICE_NAME }} \
              --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA \
              --region ${{ env.REGION }} \
              --platform managed \
              --allow-unauthenticated
